apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    olm.targetNamespaces: ibm-common-services
    olm.operatorNamespace: ibm-common-services
  name: ibm-watson-discovery-operator-subscription
  namespace: ibm-common-services    # Pick the project that contains the Cloud Pak for Data operator
spec:
  channel: v4.0
  name: ibm-watson-discovery-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
  #startingCSV: ibm-watson-discovery-operator.v4.0.2