kind: Secret
apiVersion: v1
name: "{{test_name}}"
metadata:
  annotations:
    kubernetes.io/service-account.name: zen-admin-sa
  namespace: cpd-instance
data:
  .dockerconfigjson: >-
    {{ lookup('file', '.dockerconfigjson') | b64encode }}
type: kubernetes.io/dockerconfigjson